### ISSUE TITLE
[BUG] Cloud Shell configuration, clicking `Show VNET isolation settings` resets the `Cloud Shell Region` to `Australia Central`

### ISSUE THREAD

**Issue by dozer75** [Azure/CloudShell#130]
## To Reproduce

* Create the environment following this [guide](https://docs.microsoft.com/en-us/azure/cloud-shell/private-vnet)
  * Using the `northeurope` region.
* Ensure that you don't have any Cloud Shell mounted
* Open the Cloud Shell and start the configuration
* In `You have no storage mounted`, click `Show VNET isolation settings`

## Observed Behavior
The `Cloud Shell region` is reset to the first secondary region (`Australia Central`)

## Expected behavior

It should keep the region that was selected before the `Show VNET isolation settings` checkbox was clicked. If this was a secondary region it should select the most relevant available region for the user.

## Is this specific to Cloud Shell?
Not sure if this is possible other places?

## Interface information
* Both https://shell.azure.com and https://portal.azure.com does this.
* Windows 11 with Google Chrome.

## Additional context

Not sure if this always happens (it does for me).

**Comment by jdrdavidson** [comment]
I have the same issue as of February 24.  VNET isolation settings resets cloud shell region to Austrailia Central.  THis is from portal.azure.us and shell.azure.us

**Comment by edyoung** [comment]
@robins1212 could you take a look?

**Comment by Romiko** [comment]
Hi,

I am having the same issue. Also when trying to create a cloudshell VNET Isolation. It has an error if I choose Australia East.

`Storage creation failed
Error: 400
{ "error": { "code": "InvalidLocation", "message": "The location 'australiaeast' is invalid." } }
Can't create a storage account. Please try again.`

**Comment by maertendMSFT** [comment]
> Hi,
> 
> I am having the same issue. Also when trying to create a cloudshell VNET Isolation. It has an error if I choose Australia East.
> 
> `Storage creation failed Error: 400 { "error": { "code": "InvalidLocation", "message": "The location 'australiaeast' is invalid." } } Can't create a storage account. Please try again.`
> 
> I can confirm all my resources for stortage, relaynamespace are all in Australia East.
> 
> I see the issue
> 
> **Secondary storage regions are currently not supported in Cloud Shell VNET scenarios.**
> 
> This means NO Australian Storage locations are supported. This is not great at all. When will Secondary Storage regions like Australia East / South East or Central be supported?

@Romiko, your comments are related to support for secondary regions, not an issue with the UX to set up a VNET scenario.
We have created a [discussion](https://github.com/Azure/CloudShell/discussions/222) on supporting secondary regions.

**Comment by maertendMSFT** [comment]
Moving out of current iteration as we are working on a full UX refresh.  The new UX should resolve this issue.

Keeping this issue open until new UX is public and issue is resolved.

**Comment by mbifeld** [comment]
New UX is rolled out to all public clouds, closing this issue.
