### ISSUE TITLE
[BUG] Why the UI to create the Cloudshell [in VNET isolation] connection requires storage firewall?

### ISSUE THREAD

**Issue by brwilkinson** [Azure/CloudShell#133]
When setting up the cloudshell connection into VNET isolation, it requries that.
1) azure relay has private link
2) the azure relay subnet has delegation for ACI ("Microsoft.ContainerInstance/containerGroups")
3) the azure relay subnet has a service endpoint for storage ("Microsoft.Storage")
4) The storage account firewall explicitly allows connectivity from the subnet
    - it will not be an option to set this up (in the UI) without this, however the specification is simply that you must be able to reach the storage account.
        -  There are at least 2 ways to implement this other than explicitly allowing this in the firewall rules
            1) Allow for all networks
            1) Enable private link on the storage account to a separate subnet in the same vnet.

Personally I would prefer not to require steps 3 and 4 above. I would simply like to enable private link on the Relay and also on the Storage Account. That would be a cleaner/more modern solution to configure.

So I guess I was wondering if there was a actual technical limitation of how it currently only shows storage accounts that have steps 3 and 4 completed, when technically, it shouldn't be a pre-requisite to actually having physical connectivity? 

AB#14681355

**Comment by theJasonHelmick** [comment]
@theJasonHelmick - Add to documentation
