### ISSUE TITLE
Use a newer base OS image

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/CloudShell#14]
Ok I'll start ;)

This issue is to track moving to a newer version of Ubuntu - 18.04 or 20.04.

I really want this specifically for Vim8.

**Comment by edyoung** [comment]
Since this is something we aim to do, and it's not done yet, let's keep it active.

**Comment by edyoung** [comment]
merged changes to master. Not deployed yet

**Comment by TylerLeonhardt** [comment]
@edyoung what version of vim comes with this new image? I'm curious!

**Comment by edyoung** [comment]
8.1.1401
