### ISSUE TITLE
[BUG] Upgrade Azure CLI to 2.33.1 to resolve `az vm create` issues

### ISSUE THREAD

**Issue by ssennettau** [Azure/CloudShell#145]
When running the `az vm create` command, the CLI returns an error due regarding VMCustomization.

This bug was present in the Azure CLI v2.33.0, and has since been reported to ([Issue #21224](https://github.com/Azure/azure-cli/issues/21224)) and fixed by the Azure CLI Team in [Azure CLI v2.33.1](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.33.1). The issue is still present in the Azure CLI, which is using the `v2.33.0` version.

Since the Azure Cloud Shell does not allow the Azure CLI version to be upgraded with `az upgrade`, and it uses an apparently forked version of the CLI hosted in a blob storage account (ref [tools.Dockerfile:L15](https://github.com/Azure/CloudShell/blob/e00cecbbaa276979f349550d8e67448e4fc2f301/linux/tools.Dockerfile#L15)), I cannot submit a PR to resolve the issue.

Requesting that the Cloud Shell be updated with the latest release of the Azure CLI, v2.33.1 or later.

## To Reproduce

```
az vm create --resource-group "ssennett-workrg" --name "ssennett-w2019" --image "win2019datacenter" --admin-username "testadmin" --admin-password "P@ssw0rd12345" --public-ip-sku Standard
```

## Observed Behavior

```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"'VMCustomization' is not enabled for the Subscription. Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature.\"\r\n  }\r\n}"}]}}
```

## Expected behavior

The Virtual Machine creation request should succeed

## Is this specific to Cloud Shell?

Yes. The original issue was related to the Azure CLI, but since it has been patched, the impact is specific to the Azure Cloud Shell due to the version of the Azure CLI which has been deployed

## Interface information

Directly through the Azure Portal (`portal.azure.com`), using Chrome 98.0.4758.80. Nil other issues noted.

## Additional context

The original Azure CLI Issue has been [commented noting the release of the hotfix](https://github.com/Azure/azure-cli/issues/21224#issuecomment-1038804063), with @zhoxing-ms tagging @edyoung regarding a request to update the version in the Cloud Shell image. Unknown if this is already being worked on, but adding the ticket for tracking.

**Comment by edyoung** [comment]
Cloud Shell has been upgraded to this build now.
