### ISSUE TITLE
[BUG] Issue creating new vm

### ISSUE THREAD

**Issue by Adobe-Android** [Azure/CloudShell#147]
## To Reproduce
1. Go to https://portal.azure.com
1. Open Cloud Shell
1. I have no storage mounted
1. Show advanced
1. Set Resource Group to my myRGPS
1. Create new Storage account
1. Create new File share
1. Click Create Storage
1. Create a new VM with the below command
```
New-AzVm `
-ResourceGroupName "myRGPS" `
-Name "myVMPS" `
-Location "East US" `
-VirtualNetworkName "myVnetPS" `
-SubnetName "mySubnetPS" `
-SecurityGroupName "myNSGPS" `
-PublicIpAddressName "myPublicIpPS"
```
## Observed Behavior
```
cmdlet New-AzVM at command pipeline position 1
Supply values for the following parameters:
Credential
User: Azureuser
Password for user Azureuser: ********

No Size value has been provided. The VM will be created with the default size Standard_D2s_v3.
New-AzVM: 'VMCustomization' is not enabled for the Subscription. Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature.
```

## Expected behavior

The Virtual Machine creation request should succeed.

## Is this specific to Cloud Shell?
Yes. I was able to reproduce the issue both in the browser connected to Azure Cloud Shell and when connected to Azure Cloud Shell in Windows Terminal.

I was not able to reproduce it within the Azure CLI when issuing the following commands.

```
az vm create --name "myVMPS" --resource-group "myRGPS" --location "southcentralus" --image MicrosoftWindowsServer:WindowsServer:2019-datacenter-gensecond:latest
```

## Interface information
Through https://portal.azure.com, Edge 99 on Windows 10.

## Additional context
Seems very similar to #145

**Comment by yaamas** [comment]
This seems more related to powershell than the CloudShell or Azure CLI.

```PS /home/cloud> New-AzVM `                                                     
>> -ResourceGroupName $RG `
>> -Name vm-demo-03 `
>> -Image Win2016Datacenter

cmdlet New-AzVM at command pipeline position 1
Supply values for the following parameters:
Credential
User: test-it
Password for user cloudchase: **********

New-AzVM: 'VMCustomization' is not enabled for the Subscription. Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature.
```

**Comment by maertendMSFT** [comment]
This is related to Azure PowerShell, not Cloud Shell
