### ISSUE TITLE
Additional tools requested in base cloud shell image

### ISSUE THREAD

**Issue by dsmithcloud** [Azure/CloudShell#148]
One of my global FSI customers is requesting additional database management tools be included in the base cloud shell container image.  Their security team would like to prevent data persisting between cloud shell sessions.  Because of this, they cannot add these tools to any storage account file shares (they want to use ephemeral storage.

- [Mongo shell](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Frepo.mongodb.com%2Fyum%2Fredhat%2F8%2Fmongodb-enterprise%2F4.4%2Fx86_64%2FRPMS%2Fmongodb-enterprise-shell-4.4.12-1.el8.x86_64.rpm%3F_ga%3D2.221594392.1842337724.1646210128-1933012937.1645420817&data=04%7C01%7Csmithdavid%40microsoft.com%7Ce2f308a17311464348f508da0084a730%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822867019420513%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8DpIfFBFEAPuqxJAPBE7OyZYB6q%2F3yHMUGowBeqFGSc%3D&reserved=0)
- Mongo [database tools](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.mongodb.com%2Ftry%2Fdownload%2Fdatabase-tools&data=04%7C01%7Csmithdavid%40microsoft.com%7Ce2f308a17311464348f508da0084a730%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637822867019420513%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jKsPBxS%2FR8hXOrvsZkJj33845n5KW%2FFUkUoIcBJd4E8%3D&reserved=0)
- JQ

**Comment by dsajanice** [comment]
Hi @dsmithcloud would you mind closing an re-opening this issue with a new Image update template that was added today. That would help my team triage the issue a little better. Thanks!

**Comment by dsmithcloud** [comment]
Closing this issue and opening [#150](https://github.com/Azure/CloudShell/issues/150)

**Comment by dsmithcloud** [comment]
> Hi @dsmithcloud would you mind closing an re-opening this issue with a new Image update template that was added today. That would help my team triage the issue a little better. Thanks!

Complelted.  See [#150](https://github.com/Azure/CloudShell/issues/150)
