### ISSUE TITLE
[Image Update] Add .NET 6

### ISSUE THREAD

**Issue by seesharprun** [Azure/CloudShell#164]
I created a PR (#154) a couple of weeks ago to add .NET 6 to the base image so it's side-by-side with .NET Core 3.1. These are the two current LTS versions of .NET.

The latest version of .NET and C# supports [top-level statements](https://docs.microsoft.com/dotnet/csharp/fundamentals/program-structure/top-level-statements). In a scripting scenario, it's really nice to be able to write a 2-3 line app to do something with the SDK swiftly without a bunch of plumbing code that's required by .NET Core 3.1 today.

**Comment by priyaananthasankar** [comment]
#154  Merged.
