### ISSUE TITLE
[Image Update] Helm to 3.8.2

### ISSUE THREAD

**Issue by jamote** [Azure/CloudShell#168]
This is a request to update the helm version installed with cloudshell.   With Kubernetes 1.22 helm 3.4 which is installed right now does not support some of the new API's so customers cannot update their helm releases.   This is needed du to API deprecations in 1.22

https://github.com/helm/helm/releases/tag/v3.8.2

3.8 is the version that adds support for 1.22 Updating to Kubernetes 1.22.4 packages https://github.com/helm/helm/commit/c2da47e22bde420602b46d9e6b6e3152c63f7a90 (Matt Farina)

AB#14503410

**Comment by priyaananthasankar** [comment]
Currently the following error message is seen when updating helm chart for 1.22 with current helm version is cloudshell.

"Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: [unable to recognize "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"]"

**Comment by priyaananthasankar** [comment]
@jamote : Can you help us understand what command you tried that gave the above error and what is the expected result? So that we can add the appropriate test in the command list.

**Comment by robins1212** [comment]
Running `helm version` shows that the version now installed in Cloud Shell is 3.9.0.
