### ISSUE TITLE
[Feature Request] US Gov Regions do not support VNET isolation

### ISSUE THREAD

**Issue by quantroq** [Azure/CloudShell#170]
## To Reproduce

In Azure Gov cloud, create a new Cloud Shell instance and attempt to configure for VNET isolation.

## Observed Behavior

When checking the “Show VNET isolation settings” option, it no longer shows any US Government regions as options for deploying Cloud Shell.

## Expected behavior

We should be able to use VNET isolation within Cloud Shell in US Government regions.

## Is this specific to Cloud Shell?
n/a

## Interface information
Accessing Cloud Shell via https://portal.azure.us

## Additional context
Also filed a case directly on this subject. 

AB#14440170

**Comment by hima-gadupudi** [comment]
It is supported in USGovVirginia and Arizona

![image](https://user-images.githubusercontent.com/70500138/210895512-75c35385-a59f-48ee-b72f-1ec173caad0b.png)

**Comment by quantroq** [comment]
Thank you! Will test it out.
