### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RDukes425** [Azure/CloudShell#177]
## To Reproduce

```
Commands you ran
get resource using the ResourceManagementClient which is hardcoded in doc: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L59 

## Observed Behavior

```
Include error output here
I received a customer support ticket for API version 2021-04-01 not being support in either AzureCloud or AzureUSGovernment for the ResourceManagementClient module of the SDK,
An example of the Error being received is:

Azure Cloud
azure.core.exceptions.HttpResponseError: (NoRegisteredProviderFound) No registered resource provider found for location 'eastus' and API version '2021-04-01' for type 'workspaces'. The supported api-versions are '2015-03-20, 2015-11-01-preview, 2017-01-01-preview, 2017-03-03-preview, 2017-03-15-preview, 2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2020-10-01, 2021-06-01, 2021-03-01-privatepreview, 2021-12-01-preview'. The supported locations are 'eastus, westeurope, southeastasia, australiasoutheast, westcentralus, japaneast, uksouth, centralindia, canadacentral, westus2, australiacentral, australiaeast, francecentral, koreacentral, northeurope, centralus, eastasia, eastus2, southcentralus, northcentralus, westus, ukwest, southafricanorth, brazilsouth, switzerlandnorth, switzerlandwest, germanywestcentral, australiacentral2, uaecentral, uaenorth, japanwest, brazilsoutheast, norwayeast, norwaywest, francesouth, southindia, koreasouth, jioindiacentral, jioindiawest, canadaeast, westus3, swedencentral'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'eastus' and API version '2021-04-01' for type 'workspaces'. The supported api-versions are '2015-03-20, 2015-11-01-preview, 2017-01-01-preview, 2017-03-03-preview, 2017-03-15-preview, 2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2020-10-01, 2021-06-01, 2021-03-01-privatepreview, 2021-12-01-preview'. The supported locations are 'eastus, westeurope, southeastasia, australiasoutheast, westcentralus, japaneast, uksouth, centralindia, canadacentral, westus2, australiacentral, australiaeast, francecentral, koreacentral, northeurope, centralus, eastasia, eastus2, southcentralus, northcentralus, westus, ukwest, southafricanorth, brazilsouth, switzerlandnorth, switzerlandwest, germanywestcentral, australiacentral2, uaecentral, uaenorth, japanwest, brazilsoutheast, norwayeast, norwaywest, francesouth, southindia, koreasouth, jioindiacentral, jioindiawest, canadaeast, westus3, swedencentral'.

Azure US Government
Same Error about the API

Can you please onboard the API since it is called out in the Github article as Default?
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/_resource_management_client.py#L59

## Expected behavior

Expect the execution of the command to return results for get resource in Python SDK

## Is this specific to Cloud Shell?
Issue is happening with Azure SDK for Python

## Additional context
Created Issue: https://github.com/Azure/azure-rest-api-specs/issues/18857

**Comment by edyoung** [comment]
Thanks for the report. However as far as I can see this is not an issue with Cloud Shell itself - Cloud Shell is the web-based terminal which allows you run a number of different tools, including AZ CLI. I would recommend filing an issue against azure-sdk-for-python itself. Cloud Shell will be updated to the latest version when they ship updates.

If I have misunderstood somehow and the issue is related to Cloud Shell, please clarify the connection.

Thanks!

**Comment by RDukes425** [comment]
Hello, there was a issue posted on the Python side. I was informed by Danny Maertens to submit for Azure Cloud Shell. 

Please see: https://github.com/Azure/azure-rest-api-specs/issues/18857
