### ISSUE TITLE
[BUG] Australia has no Cloud Shell Support

### ISSUE THREAD

**Issue by Romiko** [Azure/CloudShell#178]
## To Reproduce
Try deploy cloudshell with vnet isolation with storage in either Australia East, Australia Central or Australia South East

Commands you ran
Just use the normal Cloud Shell VNET isolation templates and use Australia East

## Observed Behavior

 Australia East is invalid

```
Include error output here

Storage creation failed Error: 400 { "error": { "code": "InvalidLocation", "message": "The location 'australiaeast' is invalid." } } Can't create a storage account. Please try again.
```

## Expected behavior

Australia should at the very least have ONE PRIMARY REGION. You cannot have all of Australia be secondary. This does not make sense from a data sovereignty perspective. When will this be supported?

## Is this specific to Cloud Shell?
Yes, Cloud Shell does not support storage in Secondary Regions.

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com, via Windows Terminal, or some other method?

portal.azure.com

## Additional context

I know Secondary Regions is not supported, but at the very least, allow one location from Australia, otherwise we have to look elsewhere for a solution. We cannot have our data sit in South East Asia.

AB#14439757

**Comment by dsajanice** [comment]
Assigning to @hima-gadupudi for investigation.

**Comment by hima-gadupudi** [comment]
Added support for AustraliaEast. Now, CloudShell customers can launch vnet shell in AustraliaEast region.
