### ISSUE TITLE
[BUG] Broken - Azure cloud shell maven version - OpenJDK 17 conflict

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/CloudShell#180]
## To Reproduce
Clone this repo onto cloud shell: https://github.com/spring-petclinic/spring-petclinic-microservices
Run `mvn clean compile` 
```
Commands you ran
```
`mvn clean compile`
## Observed Behavior
Command fails to run
```
Include error output here
```

## Expected behavior

The command should run

## Is this specific to Cloud Shell?
Please verify if the same issue can be reproduced by running the same tool **outside Cloud Shell** - for example,
by installing it on your own computer. If so, it is likely to be a bug in that tool or in the Azure service it communicates with, 
not in Cloud Shell. Please file the issue with the appropriate project.

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com, via Windows Terminal, or some other method?
If a browser, which Operating System and browser are you using? (ex. Edge on Windows 10)

## Additional context

AB#14442671

**Comment by karianna** [comment]
Basically Cloudshell needs to upgrade to Maven 3.8.4 and this will be resolved.

**Comment by priyaananthasankar** [comment]
Adding specific maven version to the shell, as the debian package mirror downloads the older version and is end of life.

**Comment by priyaananthasankar** [comment]
Fixed - will be available in next production release - approximate ETA 1-2 weeks from now.

**Comment by bayanlouzi** [comment]
Hello , Any information about the fic ETA ?

**Comment by priyaananthasankar** [comment]
@bayanlouzi : Fixed and available in production. Check again.
