### ISSUE TITLE
[BUG] Lint and optimize the docker files

### ISSUE THREAD

**Issue by asears** [Azure/CloudShell#19]
## To Reproduce

Run a linter on CloudShell/linux/base.Dockerfile

Using tools such as <https://www.fromlatest.io/#/> will identify some issues with the docker files for stability (apt-get update missing -y) and Optimization.  The dockerfiles in this repo may benefit from less RUN and COPY commands and multi-stage builds.  Though this may increase the build times.

The apt cache could be removed if not being done.
<https://gist.github.com/marvell/7c812736565928e602c4>

## Observed Behavior

```plaintext
Line 124: Missing parameter for `apt-get` (Possible Bug)
Line 184: Missing parameter for `apt-get` (Possible Bug)
Line 13: apt-get update with matching cache rm (Optimization)
Line 13: Consider `--no-install-recommends` (Optimization)
Line 72: apt-get update with matching cache rm (Optimization)
Line 72: Consider `--no-install-recommends` (Optimization)
Line 124: Consider `--no-install-recommends` (Optimization)
Line 130: apt-get update with matching cache rm (Optimization)
Line 130: Consider `--no-install-recommends` (Optimization)
Line 184: apt-get update with matching cache rm (Optimization)
Line 184: Consider `--no-install-recommends` (Optimization)
Line 257: Consider `--no-install-recommends` (Optimization)
```

## Expected behavior

It would be beneficial to the community and MS that the image size remains as small as possible and well-optimized.

## Is this specific to Cloud Shell?

N/A

## Interface information

N/A

## Additional context

Other possible tools to run in build:  
<https://github.com/projectatomic/dockerfile_lint>
<https://github.com/hadolint/hadolint>

**Comment by darrentu** [comment]
@asears  Thanks for bringing this up. We do realize that there are a couple optimizations we can make. However, we are planning to do that after our change in the base image (which will happen very soon). We will change our base image from Ubuntu:16.04 to CBL-D (a Microsoft compliant OS based off of Debian:10).
