### ISSUE TITLE
Update Node to v10.x

### ISSUE THREAD

**Issue by markjbrown** [Azure/CloudShell#207]
Thank you for filing this request! Please take a few minutes to fill out this template so that we can better understand the request.

#### Which image would you like to change?
Not sure

#### What changes are you requesting?
Bump the version of Node to 10+ from 8.6.

#### What scenario are these changes enabling?
MongoDB drivers require 10+ and we’re trying to build labs for Microsoft Learn Labs platform that execute in the Cloud Shell for exercises we are creating for Azure Cosmos DB's MongoDB API.

#### By how much does this change change the image size?
Not sure

**Comment by maertendMSFT** [comment]
This should be resolved in the latest image

**Comment by markjbrown** [comment]
Awesome. Thanks!!!

**Comment by davemedvitz** [comment]
As of right now, the image that I just pulled (mcr.microsoft.com/azure-cloudshell:latest) still has node 8.  The executable in the image is dated 2019.  I would have expected a 16.x version, considering that is the default on Mariner.
