### ISSUE TITLE
[BUG] clouddrive dependant on az cli default output set to tsv

### ISSUE THREAD

**Issue by cbezenco** [Azure/CloudShell#210]
## To Reproduce

setup your az cli default output to json with az config set core.output=json

Commands you ran

azureuser@Azure:~/clouddrive$ clouddrive mount -s "LAB-SAND01" -g "rg-secured-cloud-shell" -n "csrootlabnet02" -f "afs-cs-root-lab-net-02"

## Observed Behavior

INFO: Setting subscription (LAB-SAND01)
INFO: Subscription ID: 45ac8dd3-39b7-43d3-b423-63997a23959d
INFO: User Principal Name: root@lab.bezencon.net
INFO: Getting storage account (csrootlabnet02) in resource group (rg-secured-cloud-shell)
WARN: After attaching to a new file share, all your terminals will be reconnected. Please save your work before continue.
Do you want to continue?(y/n)y

Include error output here

/usr/bin/clouddrive: line 360: "1": syntax error: operand expected (error token is ""1"")

## Expected behavior

clouddrive mount should provide without error and should not have any dependancy on default az cli output format setup by the user

## Is this specific to Cloud Shell?
Please verify if the same issue can be reproduced by running the same tool **outside Cloud Shell** - for example,
by installing it on your own computer. If so, it is likely to be a bug in that tool or in the Azure service it communicates with, 
not in Cloud Shell. Please file the issue with the appropriate project.

Don't know for sure but expect same behavior

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com, via Windows Terminal, or some other method?
If a browser, which Operating System and browser are you using? (ex. Edge on Windows 10)

Edge on Windows 11

## Additional context

I suspect that line 358 should be replaced by 
 USED_SIZE=$(az storage share stats -n "$FILE_SHARE" --account-name "$STORAGE_ACCOUNT" --account-key "$KEY" -o tsv)
  
I am doing some more test to see if there are other similar issue and will submit PR

**Comment by dsajanice** [comment]
This issue will be addressed in our upcoming release that will be out next week. Please take a look at the release notes here: https://github.com/Azure/CloudShell/releases/tag/1.0.20220803.1.base.master.585b6c60
