### ISSUE TITLE
Remove maven gz file post download

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/CloudShell#217]
## To Reproduce

```
Build and run the image and you will find a apache-maven-<Release>.gz file in the / folder. Maven was already installed after unzipping this file and this zip file can then be removed.
```

## Observed Behavior

```
Maven downloaded Zip file still present in the / folder
```

## Expected behavior

Remove the zip file from the / folder

## Is this specific to Cloud Shell?
Yest

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com, via Windows Terminal, or some other method?
If a browser, which Operating System and browser are you using? (ex. Edge on Windows 10)

## Additional context
None

**Comment by maertendMSFT** [comment]
Post marinier this should be resolved
