### ISSUE TITLE
[Image Update] golang

### ISSUE THREAD

**Issue by rguptar** [Azure/CloudShell#223]
#### Which image would you like to change?
base.Dockerfile

#### What changes are you requesting?

update go 1.13 -> 1.18

#### What scenario are these changes enabling?
application development

#### By how much does this change change the image size?
negligible

**Comment by dsajanice** [comment]
We are upgrading the version of Go to 1.18.3 in our next release, which will go live in about a week. The release notes are here: https://github.com/Azure/CloudShell/releases/tag/1.0.20220803.1.base.master.585b6c60
