### ISSUE TITLE
[Image Update] Remove prerelease for powershell predictor

### ISSUE THREAD

**Issue by dsajanice** [Azure/CloudShell#229]
Thank you for filing this request! Please take a few minutes to fill out this template so that we can better understand the request.

#### Which image would you like to change?

The powershell setup script includes a prerelease flag for the PSReadLine utlity. PSReadLine now includes predictor by default, so we need to take out the prerelease flag and install the latest PSReadLine module to get predictor capability.

**Comment by theJasonHelmick** [comment]
This is planned as a future update in October.

**Comment by theJasonHelmick** [comment]
This is now removed with the release of #252.
