### ISSUE TITLE
Azure Cloud Shell Persist logs

### ISSUE THREAD

**Issue by rajivml** [Azure/CloudShell#23]
HI,

It's not a bug , but I would like to understand if there is any way we can persist the cloud shell console logs to Azure blob storage account from which the cloud shell session is originated.

For example if we running some ARM templates through Azure cloud shell and what ever logs that are generated by the commands we want to pipe these console logs to Azure blob storage, so that even if the shell terminates, we can later visit the blob storage account and check the logs to verify what happened with the last run

Is this something feasible today ?

**Comment by BellaLi** [comment]
@rajivml 
Cloud Shell has persistent storage, which is your home directory and ~/clouddrive folder. If you save any log under these two folders, you should be able to access in future cloud shell sessions.
To be specific, ~/clouddrive maps to fileshare in the storage account you provided when acquire CloudShell, and your home directory maps to the img inside of that fileshare. 
So you would need to enable the az diagnostic trace and save it under home directory, that should help.

**Comment by edyoung** [comment]
If using Powershell you can use Start-Transcript to save all the console input and output for a session to a file in your cloud drive. I believe it is possible to do the same thing with bash (search "bash transcript") but haven't tried it.

**Comment by edyoung** [comment]
Hopefully the suggestions provided work for you.
