### ISSUE TITLE
[Image Update] - please add program "screen" to cloud-shell

### ISSUE THREAD

**Issue by boliu83** [Azure/CloudShell#235]
Thank you for filing this request! Please take a few minutes to fill out this template so that we can better understand the request.

#### Which image would you like to change?
cloud-shell:latest

#### What changes are you requesting?
add program **screen**

#### What scenario are these changes enabling?
Correctly display non-unicode content.

Currently cloud-shell cannot render non-unicode content such as zh_TW.BIG5 encoded content properly.  The program "screen" acts a virtual terminal in between and can convert non-unicode content to Unicode characters using its ":encoding" command so the content can be displayed correctly in cloud-shell. 

#### By how much does this change change the image size?
Not sure, the binary "screen" is only 464KB on my Ubuntu 20.04 machine

**Comment by darrentu** [comment]
@boliu83 Hi Bo, is this a feature request? If so, would it be possible for you to create the PR? We can merge it after running our test cases.

**Comment by boliu83** [comment]
@darrentu Done.  not sure if I did the pull request correctly. let me know if you want me to change anything.

**Comment by boliu83** [comment]
thanks. any timeline for when the change is going to be available in cloud-shell ?

**Comment by darrentu** [comment]
We should have it before the middle of January 2023.

**Comment by darrentu** [comment]
Hi, @boliu83, screen has been added.
