### ISSUE TITLE
[BUG] helm push command is missing in the cloud shell, Helm version command doesn't return version number too.

### ISSUE THREAD

**Issue by KRISHNA-VKS** [Azure/CloudShell#236]
## To Reproduce
1)Last week, i was able to execute the "helm push" command to update a helm chart to the Azure container registry. But today it looks like the command is missing from the Azure Cloud shell. 

2) The Helm version command doesn't return the version number, its returning like this
command:- helm version
version.BuildInfo{Version:"v$**VERSION**", GitCommit:"", GitTreeState:"clean", GoVersion:"go1.18.3"}
```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
helm pull ingress-nginx/ingress-nginx --version 4.0.13

USER_NAME="00000000-0000-0000-0000-000000000000"
PASSWORD=$(az acr login --name $ACR_NAME --expose-token --output tsv --query accessToken)
helm registry login $ACR_FQDN --username $USER_NAME --password $PASSWORD

This step is failing for me.
**helm push** ingress-nginx-4.0.13.tgz oci://$ACR_FQDN/helm/ingress-nginx
```

## Observed Behavior

```
Error: unknown command "push" for "helm"

Did you mean this?
        pull
```

## Expected behavior

helm push should push the helm chart to the container registry. Here the command itself is missing

## Is this specific to Cloud Shell? YES
Please verify if the same issue can be reproduced by running the same tool **outside Cloud Shell** - for example,
by installing it on your own computer. If so, it is likely to be a bug in that tool or in the Azure service it communicates with, 
not in Cloud Shell. Please file the issue with the appropriate project.

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com, via Windows Terminal, or some other method? https://portal.azure.com
If a browser, which Operating System and browser are you using? (ex. Edge on Windows 10)
Chrome

**Comment by darrentu** [comment]
Hi Krishna, because of our move to the new Mariner OS, we have a new Helm version. Currently the version of Helm we are using is the latest version inside of packages.microsoft.com. If you want to get another version of Helm, please speak with the Mariner OS team - https://github.com/microsoft/CBL-Mariner.

**Comment by KRISHNA-VKS** [comment]
Thanks @darrentu for the reply. But I am still not clear what should be the next step. Couple of things are not clear
1) Helm version is not updated at "Some common Mariner packages" section of https://github.com/Azure/CloudShell/releases/tag/1.0.20220803.1.base.master.585b6c60
2) The documentation says "If your scenario has been affected by these changes, please contact Azure support, or
create an issue in the [Cloud Shell repository](https://github.com/Azure/CloudShell/issues)." 
So what should be the best option to proceed further as the command is missing.

**Comment by priyaananthasankar** [comment]
> Thanks @darrentu for the reply. But I am still not clear what should be the next step. Some things are not clear
> 
> 1. Helm version is not updated at "Some common Mariner packages" section of https://github.com/Azure/CloudShell/releases/tag/1.0.20220803.1.base.master.585b6c60
> 2. The documentation says "If your scenario has been affected by these changes, please contact Azure support, or
>    create an issue in the [Cloud Shell repository](https://github.com/Azure/CloudShell/issues)."
>    So what should be the best option to proceed further as the command is missing.
> 3. I just did a "rpm -qa" command in Azure cloud shell.
>    It says "helm-**3.4.1**-5.cm2.x86_64".
>    This is very very old release of helm. We are already in helm **3.9.3** as per release https://github.com/helm/helm/releases/tag/v3.9.3

@KRISHNA-VKS : Sorry for the inconvenience. Please find the below workaround for Helm for now. We are working to get 3.9.3 into the image and for now the ETA is 9/23 (as the release takes a bit of time)

1.	curl -fsSL -o get_helm.sh [https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fhelm%2Fhelm%2Fmain%2Fscripts%2Fget-helm-3&data=05%7C01%7CPriya.Ananthasankar%40microsoft.com%7C77b1c1f8cadc44fc517908da87a91650%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637971457539034507%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3ngBgyu4LsT0%2FzwArOVCAK8mhZdJFQNYViYJVD%2BYpNI%3D&reserved=0)
2.	chmod 700 get_helm.sh
3.	cd ~ && mkdir .local && mkdir .local/bin
4.	Inside of get_helm.sh, please change the USE_SUDO:=false and HELM_INSTALL_DIR:=$home/.local/bin
5.	./get_helm.sh

You should be able to get the latest version of Helm by following the steps above.

I will update this issue once our release is available in production.

**Comment by priyaananthasankar** [comment]
Helm 3.9.3 is now available in all clouds.
