### ISSUE TITLE
[BUG] Ansible could not deploy playbook

### ISSUE THREAD

**Issue by wangken82** [Azure/CloudShell#238]
## To Reproduce
wget https://aka.ms/nfs-cluster
unzip nfs-cluster
cd nfs-cluster-main
ansible-playbook -i hosts lab.yml

```
failed step at
 - name: Terraform apply
    terraform:
      lock: no
      force_init: true
      variables:
        cloudshell_public_ip: "{{ ipify_public_ip }}"
      project_path: './'
      state: present

```

## Observed Behavior
ansible could not deploy the playbook, failed at terraform apply
if I directly run terraform apply, it's working.

```
Include error output here
```

TASK [Terraform apply] TASK [Terraform apply] **********************************************************************************************************************************************************************************************************************
task path: /home/kenneth/nfs-cluster-main/lab.yml:22
redirecting (type: modules) ansible.builtin.terraform to community.general.terraform
redirecting (type: modules) community.general.terraform to community.general.cloud.misc.terraform
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: kenneth
<127.0.0.1> EXEC /bin/sh -c 'echo ~kenneth && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/kenneth/.ansible/tmp `"&& mkdir "` echo /home/kenneth/.ansible/tmp/ansible-tmp-1661946582.1659782-915-142039578686512 `" && echo ansible-tmp-1661946582.1659782-915-142039578686512="` echo /home/kenneth/.ansible/tmp/ansible-tmp-1661946582.1659782-915-142039578686512 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.terraform to community.general.terraform
redirecting (type: modules) community.general.terraform to community.general.cloud.misc.terraform
Using module file /opt/ansible/lib/python3.9/site-packages/ansible_collections/community/general/plugins/modules/cloud/misc/terraform.py
<127.0.0.1> PUT /home/kenneth/.ansible/tmp/ansible-local-7257z6g9g2i/tmprh5uszxw TO /home/kenneth/.ansible/tmp/ansible-tmp-1661946582.1659782-915-142039578686512/AnsiballZ_terraform.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/kenneth/.ansible/tmp/ansible-tmp-1661946582.1659782-915-142039578686512/ /home/kenneth/.ansible/tmp/ansible-tmp-1661946582.1659782-915-142039578686512/AnsiballZ_terraform.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/opt/ansible/bin/python /home/kenneth/.ansible/tmp/ansible-tmp-1661946582.1659782-915-142039578686512/AnsiballZ_terraform.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/kenneth/.ansible/tmp/ansible-tmp-1661946582.1659782-915-142039578686512/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backend_config": null,
            "backend_config_files": null,
            "binary_path": null,
            "check_destroy": false,
            "force_init": true,
            "init_reconfigure": false,
            "lock": false,
            "lock_timeout": null,
            "overwrite_init": true,
            "parallelism": null,
            "plan_file": null,
            "plugin_paths": null,
            "project_path": "./",
            "provider_upgrade": false,
            "purge_workspace": false,
            "state": "present",
            "state_file": null,
            "targets": [],
            "variables": {
                "cloudshell_public_ip": "104.215.250.160"
            },
            "variables_files": null,
            "workspace": "default"
        }
    },
    "msg": "Terraform plan could not be created\r\nSTDOUT: \r\n\r\nSTDERR: \nError: Error building AzureRM Client: Please ensure you have installed Azure CLI version 2.0.79 or newer. Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: /opt/ansible/bin/python3.9: No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed.\n\n  with provider[\"registry.terraform.io/hashicorp/azurerm\"],\n  on c1-version.tf line 10, in provider \"azurerm\":\n  10: provider \"azurerm\" {\n\n"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

kenneth [ ~/nfs-cluster-main ]$ az --version
azure-cli                         2.39.0

core                              2.39.0
telemetry                          1.0.6 *

Extensions:
ai-examples                        0.2.5
azure-cli-ml                      1.41.0
ssh                                1.1.2

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/usr/bin/python3'
Extensions directory '/home/kenneth/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.13 (main, Jul 13 2022, 05:35:38) 
[GCC 11.2.0]

## Expected behavior

A clear description of what you expected to happen instead.

## Is this specific to Cloud Shell?
yes, only found this issue on cloud shell, I tried this script in past 3 weeks,   sometimes cloudshell is working sometimes not. 
I guess some cloudshell containers not working.  

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com, via Windows Terminal, or some other method?
from chrom or Edge ,both tried

**Comment by priyaananthasankar** [comment]
@wangken82 : Is there a workaround that you are using for making this work in Cloud Shell? Just want to assess and prioritize the fix.

**Comment by wangken82** [comment]
@priyaananthasankar  Trying to debug today, but it's working now... not sure what's happened on the backend, will monitor it thx

**Comment by maertendMSFT** [comment]
Closing as issue is resolved
