### ISSUE TITLE
Can't remove Azure CLI ML extension v1 to replace with v2

### ISSUE THREAD

**Issue by theJasonHelmick** [Azure/CloudShell#244]
## To Reproduce
az extension remove -n azure-cli-ml

Using Docs @ https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli?tabs=public

```

## Observed Behavior
Failed to delete - permission denied
```

## Expected behavior
To remove the extension

**Comment by maertendMSFT** [comment]
Closing with this pr: https://github.com/Azure/CloudShell/pull/246
