### ISSUE TITLE
[BUG] Vim 9.0 colorscheme support - no syntax highlighting

### ISSUE THREAD

**Issue by richeney** [Azure/CloudShell#245]
Vim has recently been updated to v9.0 in the image. The coloured syntax highlighting is not working for me and vim is monochrome. 

Vim is recognising the filetypes correctly (`:set filetype?`). Looking at the colorscheme support (`:colorscheme `, `CTRL`+`D`), there is only desert in there.

I installed vim 9.0 into Ubuntu on WSL2 and colorscheme support was fine there.

Is there something that needs to be done to add the colorscheme support back in for the container?

**Comment by acederberg** [comment]
@richeney I was looking for a solution for exactly this! I would prefer to edit with syntax highlighting. Same symptoms - I have a colorscheme (gruvbox) and a filetype (ps1) yet no color.

**Comment by hima-gadupudi** [comment]
Currently CloudShell support supports default vim color scheme. If you want more colors in your shell, please follow the instructions below and install the color schemes you like.

Step-1: Create "colors" dir in your homedir. Change cwd to colos dir. 

-  _cd .vim_
- _mkdir colors_
- _cd colors_

Step-2: Perform wget on the color scheme that you are interested in. Showing an example for lunaperche colors cheme to install. 

- _wget https://raw.githubusercontent.com/vim/colorschemes/master/colors/lunaperche.vim_

Start using installed color schemes in your vim.

**Comment by richeney** [comment]
I should have mentioned that I am comfortably using .vim file. (I created my own [cloudshell](https://git.io/JI3fX) colorscheme to match the standard colours, which I install using an [Ansible role](https://github.com/richeney/ansible-wsl-colours).)

The issue with the Cloud Shell image is that there is 

1. only desert (and any user installed schemes)

    In vim if you type `:colo` it will show the current scheme; `:colo ` and `CTRL`+`D` then it lists out the available schemes.

2. no syntax highlighting

## WSL running jammy

![image](https://user-images.githubusercontent.com/24895350/213663855-871947d3-ca62-4094-8e43-bf178f206cb7.png)

* syntax highlighting ✅
* full set of schemes ✅

## Cloud Shell in Windows Terminal

![image](https://user-images.githubusercontent.com/24895350/213663980-ff1e8617-3a9d-4641-91f7-f199541d89e1.png)

* syntax highlighting ❌
* full set of schemes ❌

## Cloud Shell in the browser

![image](https://user-images.githubusercontent.com/24895350/213664325-adebb2eb-0761-4fb6-b0df-bc33ee57bfb9.png)

* syntax highlighting ❌
* full set of schemes ❌

@hima-gadupudi, would you reopen the issue?

**Comment by nathanweeks** [comment]
Lack of syntax highlighting support in Azure Cloud Shell's vim is still an issue.

**Comment by nathanweeks** [comment]
#384 proposes adding the vim-extra package to the Cloud Shell base image to resolve this issue.

In the interim, one could manually install vim runtime files in their Cloud Shell home directory as described at https://www.vim.org/runtime.php.  I'm familiar with vim / runtime version compatibility guarantees; if one wants to install the version of the runtime associated with their exact version of vim, the instructions could be adapted thus:

```sh
$ vim --version | head -n 2
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar  1 2024 01:01:28)
Included patches: 1-2121
$ VIMVERSION=$(vim --version | awk 'NR==1 {v=$5; FS="-"} NR == 2 {t=$2} END {print v "." t}')
$ echo $VIMVERSION
9.0.2121
$ mkdir -p ~/.vim
$ wget -O - https://github.com/vim/vim/archive/refs/tags/v${VIMVERSION}.tar.gz | tar -C ~/.vim -xzf -  vim-${VIMVERSION}/runtime/ --strip-components=2
```

**Comment by kid1412621** [comment]
> #384 proposes adding the vim-extra package to the Cloud Shell base image to resolve this issue.
> 
> 
> 
> In the interim, one could manually install vim runtime files in their Cloud Shell home directory as described at https://www.vim.org/runtime.php.  I'm familiar with vim / runtime version compatibility guarantees; if one wants to install the version of the runtime associated with their exact version of vim, the instructions could be adapted thus:
> 
> 
> 
> ```sh
> 
> $ vim --version | head -n 2
> 
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar  1 2024 01:01:28)
> 
> Included patches: 1-2121
> 
> $ VIMVERSION=$(vim --version | awk 'NR==1 {v=$5; FS="-"} NR == 2 {t=$2} END {print v "." t}')
> 
> $ echo $VIMVERSION
> 
> 9.0.2121
> 
> $ mkdir -p ~/.vim
> 
> $ wget -O - https://github.com/vim/vim/archive/refs/tags/v${VIMVERSION}.tar.gz | tar -C ~/.vim -xzf -  vim-${VIMVERSION}/runtime/ --strip-components=2
> 
> ```

Thanks for the temp fix. Why this issue had been closed as the problem still exists.
