### ISSUE TITLE
[BUG] Continuous Integration github action is failing consistently

### ISSUE THREAD

**Issue by edyoung** [Azure/CloudShell#250]
## To Reproduce

```
See https://github.com/Azure/CloudShell/actions/runs/3216116011/jobs/5257690072#step:5:41
```

## Observed Behavior

```
Expected versions don't match found versions
```

## Expected behavior

Should be simple enough to clear up and will help others contribute to cloud shell confidently.

**Comment by darrentu** [comment]
I modified the test cases to remove those commands. I think we need to have a discussion as to what the most effective approach would be for the command list
