### ISSUE TITLE
Increase storage size of user home directory

### ISSUE THREAD

**Issue by VikasPullagura-MSFT** [Azure/CloudShell#265]
Issue with Increase storage size of user home directory.

 I used the file share to increase the size of the quota, but my /dev/loop0 is only 5G so I am unable to access anything through my cloud shell for my Kubernetes cluster.
 
 
![image](https://user-images.githubusercontent.com/48944027/206236993-2bb99eb9-ea60-4bcf-aff0-7246b7304b62.png)

![image](https://user-images.githubusercontent.com/48944027/206237014-776af0ed-6985-4af0-83b0-630f162a1a6e.png)

## Additional context
Issue reported on Microsoft Q&A Platform [here](https://learn.microsoft.com/en-us/answers/questions/1119030/index.html).
Field this issue here as this is a Cloud Shell issue.

**Comment by edyoung** [comment]
Put larger files in ~/clouddrive - that's a full Azure File share you can extend to be TBs if you like. Unfortunately it's more difficult for us to resize the home directory.

**Comment by maertendMSFT** [comment]
Closing as this as edyoung's response is accurate.  @VikasPullagura-MSFT, please reopen the issue if further follow-up is needed.
