### ISSUE TITLE
Capturing Azure Cloud Shell Web Preview URL

### ISSUE THREAD

**Issue by Abhinavgundapaneni** [Azure/CloudShell#273]
We are using the Azure Cloud Shell Web preview option to run a web application on the shell and I understand that it creates a proxy URL to access the server. Is there any CLI command or SDK to get this URL Programmatically?

**Comment by darrentu** [comment]
@Abhinavgundapaneni The command `curl -H "Content-Type: application/json" -X POST http://localhost:8888/ports/$@/open;` should help. You need to replace `$@` with the port you would like to open. This command would allow you to open up a port through the CLI. If the port is already opened, it also would let you know that it is open. 
Credit: @robins1212

**Comment by darrentu** [comment]
The command curl -H "Content-Type: application/json" -X POST http://localhost:8888/ports/$@/open; should work. You need to replace $@ with the port you would like to open. This command would allow you to open up a port through the CLI. If the port is already opened, it also would let you know that it is open.
Credit: @robins1212

**Comment by theJasonHelmick** [comment]
@Abhinavgundapaneni - thank you for this issue -- @darrentu has responded with the answer -- please let us know if you need further assistance.
