### ISSUE TITLE
[Image Update] Add Redis CLI

### ISSUE THREAD

**Issue by maskati** [Azure/CloudShell#275]
#### Which image would you like to change?
base

#### What changes are you requesting?
Include `redis-cli` from `redis-tools`.

#### What scenario are these changes enabling?
Managing private [Azure Cache for Redis](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-redis-cli-tool).

#### By how much does this change change the image size?
1-5MB.

**Comment by dsajanice** [comment]
@maskati thanks for your request. Would you feel comfortable submitting a PR to our repo?

**Comment by dsajanice** [comment]
Please take a look at the redis packages listed here: https://packages.microsoft.com/cbl-mariner/2.0/prod/base/x86_64/ and see if they work for you. If they don't please let us know and we will talk to internal teams to include the tools you need.

**Comment by maskati** [comment]
@dsajanice PR #277

**Comment by darrentu** [comment]
@maskati Just out of curiosity, have you tried installing Redis locally through something like - https://techmonger.github.io/40/redis-without-root/. Have you looking into the `az redis` commands?

**Comment by maskati** [comment]
It is possible to install separately, but this also requires local build. `az redis` provides management of the Azure Cache for Redis resource, but no interface to the database itself (for example for performing CRUD operations). Redis is a widely used Azure database, so it would make sense for cloud shell to include management tooling similarly to mssql (bcp/sqlcmd), mysql, and postgresql tools.

**Comment by theJasonHelmick** [comment]
This is being added with this pr #278 -- For planning, we expect this to be available publicly in March.
