### ISSUE TITLE
[Image Update] Add user to sudoers

### ISSUE THREAD

**Issue by rguptar** [Azure/CloudShell#288]
#### Which image would you like to change?
linux

#### What changes are you requesting?
Add user to sudoers group.

#### What scenario are these changes enabling?
Allows user to update packages to the latest version via `tdnf update` and install other utility packages.

#### By how much does this change change the image size?
n/a

**Comment by dsajanice** [comment]
We'll discuss this issue internally. I will close this issue and have moved the topic to https://github.com/Azure/CloudShell/discussions/291
