### ISSUE TITLE
Error when building using Azure Devops pipeline

### ISSUE THREAD

**Issue by dthilagan** [Azure/CloudShell#29]
## To Reproduce

```
Commands you ran

ADO Pipeline to build image:

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

variables:
  imageName: 'base_cloudshell'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: linux/base.Dockerfile
```

## Observed Behavior

Build errors after 7 to 8 minutes

```
Error:

Step 21/64 : COPY ./linux/blobxfer /usr/local/bin
COPY failed: stat /var/lib/docker/tmp/docker-builder951648395/linux/blobxfer: no such file or directory
##[error]COPY failed: stat /var/lib/docker/tmp/docker-builder951648395/linux/blobxfer: no such file or directory
##[error]The process '/usr/bin/docker' failed with exit code 1

```

## Expected behavior

Since i am able to build the docker images locally, i was expecting the ADO Agents to build the image using an ADO Pipeline

## Is this specific to Cloud Shell?
Specific to ADO Pipeline builds.  No issue building on my PC.

**Comment by edyoung** [comment]
Just so I understand: you want to have your own pipeline build, this isn't something you see in our GitHub pipeline, right?

Unfortunately I won't have time to investigate for a while. Suggest looking at the logs immediately before this to see why blobxfer is not present in the image.

**Comment by dsajanice** [comment]
No further action being taken here. Please reopen if there is an ask on this topic.
