### ISSUE TITLE
[BUG] - rsync is missing

### ISSUE THREAD

**Issue by xpillons** [Azure/CloudShell#30]
## To Reproduce

```
rsync
```

## Observed Behavior

```
xavier@Azure:~$ rsync
bash: rsync: command not found
```

## Expected behavior

rsync was working on Aug-10, and not anymore now

## Is this specific to Cloud Shell?
yes

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com
If a browser, which Operating System and browser are you using? Edge on Windows 10

**Comment by BellaLi** [comment]
CloudShell didn't install this tool specifically, not sure why it became missing. We'll do some investigation. Thanks for reporting.

**Comment by BellaLi** [comment]
rsync should be back now. Please double check. Thanks. @xpillons

**Comment by xpillons** [comment]
I confirm it's there now
