### ISSUE TITLE
[BUG] The Docker Daemon

### ISSUE THREAD

**Issue by darrentu** [Azure/CloudShell#31]
## To Reproduce

```
dockerd
```

## Observed Behavior

```
dockerd needs to be started with root. To see how to run dockerd in rootless mode with unprivileged user, see the documentation
```

## Expected behavior

Is there a possible way for me to run the docker daemon in Cloud Shell? If not, should we remove the `moby-engine` command?  Should we consider a rootless docker daemon? (https://medium.com/@tonistiigi/experimenting-with-rootless-docker-416c9ad8c0d6)

## Is this specific to Cloud Shell?
Yes

## Interface information
https://portal.azure.com and through my personal laptop
Operating system: Chrome

**Comment by edyoung** [comment]
Cloud shell runs in a container and the user runs as unprivileged. We don't know of a way to allow users to successfully run docker with these constraints. We may re-evaluate in the future, but for now I will resolve this as out of scope for us. Sorry about that.
