### ISSUE TITLE
[Improvement] Consider updating the version of the SQLServer PowerShell module to v22

### ISSUE THREAD

**Issue by Matteo-T** [Azure/CloudShell#314]
Currently, the logic in the DockerFiles and setup files cap the version of the SQLServer PowerShell module to v21.

That was a mechanism we put in place to avoid accidentally picking up breaking changes.

Well, now that I released v22 of the module (which does have breaking changes compare to v21), it would be nice to see if we can look into updating it.

While the change is probably trivial, I'm more concerned about breaking people out there - is there a way to have the change rolled out in stages or get a sense of how people may be affected? Maybe we could install both v21 and v22 SxS to allow people to opt out of v22 and go back to v21 should they see problems?

**Comment by dsajanice** [comment]
@Matteo-T @darrentu  has created a PR for this: https://github.com/Azure/CloudShell/pull/316. Please take a look and approve if it looks ok.

**Comment by darrentu** [comment]
Closing this because changes are complete and are in production
