### ISSUE TITLE
[BUG} Error code after open powershell   Via  https://portal.azure.com

### ISSUE THREAD

**Issue by eakarat1141** [Azure/CloudShell#333]
## To Reproduce

open powershell 

```
Commands you ran
```

## Observed Behavior
Requesting a Cloud Shell.Succeeded. 
Connecting terminal...

Welcome to Azure Cloud Shell

Type "az" to use Azure CLI
Type "help" to learn about Cloud Shell

Import-Module: /opt/microsoft/powershell/7/profile.ps1:13
Line |
  13 |  Microsoft.PowerShell.Core\Import-Module -Name PSCloudShellUtility
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This module requires Az.Accounts version 2.12.3. An earlier version of
     | Az.Accounts is imported in the current PowerShell session. Please open a
     | new session before importing this module. This error could indicate that
     | multiple incompatible versions of the Azure PowerShell cmdlets are
     | installed on your system. Please see https://aka.ms/azps-version-error
     | for troubleshooting information.
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:308
Line |
 308 |  & ($script:PSCloudShellUtilityModuleInfo){Get-CloudShellTip -ErrorAct …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that
     | was not valid. It must result in a command name, a script block, or a
     | CommandInfo object.
VERBOSE: Authenticating to Azure ...
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:64
Line |
  64 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that
     | was not valid. It must result in a command name, a script block, or a
     | CommandInfo object.
Invoke-CloudShellTelemetry: /opt/microsoft/powershell/7/profile.ps1:95
Line |
  95 |          Invoke-CloudShellTelemetry -LogLabel "GETSUBSCRIPTIONID" -Sta …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that
     | was not valid. It must result in a command name, a script block, or a
     | CommandInfo object.
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:64
Line |
  64 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that
     | was not valid. It must result in a command name, a script block, or a
     | CommandInfo object.
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:64
Line |
  64 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that
     | was not valid. It must result in a command name, a script block, or a
     | CommandInfo object.
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:64
Line |
  64 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that
     | was not valid. It must result in a command name, a script block, or a
     | CommandInfo object.
Import-Module: /opt/microsoft/powershell/7/profile.ps1:395
Line |
 395 |      Microsoft.PowerShell.Core\Import-Module -Name AzurePSDrive
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This module requires Az.Accounts version 2.12.3. An earlier version of
     | Az.Accounts is imported in the current PowerShell session. Please open a
     | new session before importing this module. This error could indicate that
     | multiple incompatible versions of the Azure PowerShell cmdlets are
     | installed on your system. Please see https://aka.ms/azps-version-error
     | for troubleshooting information.
VERBOSE: Building your Azure drive ...
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:64
Line |
  64 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that
     | was not valid. It must result in a command name, a script block, or a
     | CommandInfo object.
New-PSDrive: /opt/microsoft/powershell/7/profile.ps1:406
Line |
 406 |      $null = Microsoft.PowerShell.Management\New-PSDrive -Name Azure - …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find a provider with the name 'SHiPS'.
WARNING: Something went wrong while creating Azure drive. You can still use this shell to run Azure PowerShell commands.
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:64
Line |
  64 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that
     | was not valid. It must result in a command name, a script block, or a
     | CommandInfo object.
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:419
Line |
 419 |  & ($script:PSCloudShellUtilityModuleInfo){Set-CloudShellPSReadLineKey …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that
     | was not valid. It must result in a command name, a script block, or a
     | CommandInfo object.
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:64
Line |
  64 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that
     | was not valid. It must result in a command name, a script block, or a
     | CommandInfo object.
PS /home/eakarat> 
Include error output here

![image](https://github.com/Azure/CloudShell/assets/61174321/e90edd5a-7ca9-42fb-b4a8-f5673d1c87a4)
![image](https://github.com/Azure/CloudShell/assets/61174321/f5d885b5-f0bc-400e-97be-856812d85d9f)

## Expected behavior

A clear description of what you expected to happen instead.

## Is this specific to Cloud Shell?
Please verify if the same issue can be reproduced by running the same tool **outside Cloud Shell** - for example,
by installing it on your own computer. If so, it is likely to be a bug in that tool or in the Azure service it communicates with, 
not in Cloud Shell. Please file the issue with the appropriate project.

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com, via Windows Terminal, or some other method?
If a browser, which Operating System and browser are you using? (ex. Edge on Windows 10)

Via  https://portal.azure.com
## Additional context

How to fix the error to disappear?

**Comment by theJasonHelmick** [comment]
Thank you @eakarat1141 for reporting this issue.  The error message states that you are loading a different version of AZ.Accounts than the one required.  "This module requires Az.Accounts version 2.12.3. An earlier version of | Az.Accounts is imported in the current PowerShell session. "

You can check check to see if you have an older module installed by running Get-Module -Name Az.Accounts.  You can then remove the older module versions with Uninstall-module.
