### ISSUE TITLE
[Image Update] to include cpio

### ISSUE THREAD

**Issue by marcindulak** [Azure/CloudShell#339]
#### Which image would you like to change?

base

#### What changes are you requesting?

cpio

#### What scenario are these changes enabling?

Sometimes cloud shell needs packages that are not installed (see for  example #338).
Since there is no sudo access, a way to install packages is to unpack an existing rpm,
for example from a RHEL8-based system.

```
rpm2cpio package*.rpm | cpio -idvm
```

#### By how much does this change change the image size?

About 1MB https://centos.pkgs.org/9-stream/centos-baseos-x86_64/cpio-2.13-16.el9.x86_64.rpm.html

**Comment by theJasonHelmick** [comment]
duplicate: #348
