### ISSUE TITLE
[Image Update] Need cpio package to utilize "rpm2cpio" package in cloudshell

### ISSUE THREAD

**Issue by hima-gadupudi** [Azure/CloudShell#348]
Thank you for filing this request! Please take a few minutes to fill out this template so that we can better understand the request.

#### Which image would you like to change?
Base/ tools image

#### What changes are you requesting?
Would like to get cpio pacakge. Currently cloudshell image container rpm2cpio package. But without cpio package, this cannot be used properly.
https://packages.microsoft.com/cbl-mariner/2.0/prod/base/x86_64/Packages/c/cpio-2.13-4.cm2.x86_64.rpm

#### What scenario are these changes enabling?

![image](https://github.com/Azure/CloudShell/assets/70500138/bd3faa00-fddf-4e08-8c30-b907f3c56c8b)

#### By how much does this change change the image size?
239KB

**Comment by darrentu** [comment]
A `tdnf install cpio` should resolve this issue. I think it should be fine to add this into our base.

**Comment by marcindulak** [comment]
Cloud Shell does not provide sudo access to install packages with tdnf.

cpio was requested already in https://github.com/Azure/CloudShell/issues/339

**Comment by theJasonHelmick** [comment]
Thank you @hima-gadupudi for reporting this issue -- The ETA for this release is 9/21/2023
