### ISSUE TITLE
[BUG] SSH password login is no longer working

### ISSUE THREAD

**Issue by DenisBPCS** [Azure/CloudShell#349]
## To Reproduce
This used to work until a couple of days ago. Basically all you need to do is to try and SSH into a server using a SSH password.
```
ssh -l user server
```

## Observed Behavior
```
ssh user@host   
Permission denied, please try again.
Permission denied, please try again.
user@host: Permission denied (publickey,password).
```

Using `-v` in the command revealed the following output
```
...
debug1: Next authentication method: password
debug1: read_passphrase: can't open /dev/tty: No such file or directory
...
```

## Expected behavior

The `ssh` command should ask for the password needed to SSH into the host.

## Is this specific to Cloud Shell?
This is specific to CloudShell. Tried both Powershell and Bash as well.

## Interface information
Accessing the Cloud Shell through https://portal.azure.com using Chrome on a MacOS Ventura 13.5.1 

## Additional context
```
> ls -la /dev/tty
/usr/bin/ls: cannot access '/dev/tty': No such file or directory
> tty                                                                                                                                                         
/dev/pts/4
> 
```

**Comment by lordfolken** [comment]
A lot of tools don't work without the /dev/tty file... this was there before. Please urgently fix this.
kustomize
git
k9s

**Comment by lordfolken** [comment]
Sudo doesn't work either:
```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```

**Comment by lordfolken** [comment]
Today i login in azure cloud shell, and the file is again present:
```
$ stat /dev/tty
  File: /dev/tty
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 4eh/78d Inode: 10          Links: 1     Device type: 5,0
Access: (0666/crw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-09-07 11:26:25.153990721 +0000
Modify: 2023-09-07 11:26:25.153990721 +0000
Change: 2023-09-07 11:26:25.153990721 +0000
 Birth: -
```
So I believe this bug to be fixed now.

**Comment by DenisBPCS** [comment]
Yes, password prompting works now. Closing the issue. Thanks!
