### ISSUE TITLE
The "Open editor { }" on azure cloud shell does not work properly now I have to reload the terminal, damn fix this pls.[BUG]

### ISSUE THREAD

**Issue by Sipho-Haraba-Tesladigitech** [Azure/CloudShell#357]
## To Reproduce

```
Commands you ran
```

## Observed Behavior

```
Include error output here
```

## Expected behavior

A clear description of what you expected to happen instead.

## Is this specific to Cloud Shell?
Please verify if the same issue can be reproduced by running the same tool **outside Cloud Shell** - for example,
by installing it on your own computer. If so, it is likely to be a bug in that tool or in the Azure service it communicates with, 
not in Cloud Shell. Please file the issue with the appropriate project.

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com, via Windows Terminal, or some other method?
If a browser, which Operating System and browser are you using? (ex. Edge on Windows 10)

**Comment by edyoung** [comment]
It worked when I tried it. @Sipho-Haraba-Tesladigitech do you see this consistently? what browser & OS are you using?

**Comment by theJasonHelmick** [comment]
Hi @Sipho-Haraba-Tesladigitech - thank you for reporting this issue.  Can you describe your experience including how often this occurs, the operating system/browser your using, along with which shell you were working in (Bash or PowerShell) so we can investigate?

**Comment by mbifeld** [comment]
Closing as no response from issuer.
