### ISSUE TITLE
[BUG] .NET Core version is not up to date

### ISSUE THREAD

**Issue by cdennig** [Azure/CloudShell#37]
## To Reproduce

Open https://shell.azure.com (bash or PS) and run...

```
dotnet --list-sdks
```

## Observed Behavior

Only up to version 2.2 is installed.

```
1.0.1 [/usr/share/dotnet/sdk]
2.2.402 [/usr/share/dotnet/sdk]
```

## Expected behavior

The documentation [here](https://docs.microsoft.com/en-us/azure/cloud-shell/features) says, that **.NET Core version 3.1.302** is supported in Azure Cloud Shell....which is not the case. When you start a shell, you can only use up to SDK version 2.2. Looking at the docker image, it only includes version 2.2:

https://github.com/Azure/CloudShell/blob/6ca2afc124b4e4dd22eddc41fea5b41db3509096/linux/base.Dockerfile#L80

## Is this specific to Cloud Shell?

Yes.

## Interface information

https://shell.azure.com - but as described above, it's not a problem with UI/UX of the shell itself.

**Comment by cdennig** [comment]
Any chance this will be fixed? Multiple .NET Core versions should not be a problem at all as you can choose the version per project/folder with a global.json.

**Comment by edyoung** [comment]
We have a major revision of a number of packages in the works, see cbl-d branch for details. Will include upgrade to. Net core sdk in that.

**Comment by cdennig** [comment]
Great to hear. Thanks for the update.

**Comment by edyoung** [comment]
merged changes to master. Not deployed yet
