### ISSUE TITLE
kubectl need update, since some AKS features require version 1.18.1

### ISSUE THREAD

**Issue by ma-ha** [Azure/CloudShell#38]
## To Reproduce

Create AKS with managed Azure AD feature;
https://docs.microsoft.com/en-us/azure/aks/managed-aad

kubectl can't login any more

## Observed Behavior

kubectl can't login any more to most recent AKS

## Expected behavior

An updated version of kubectl works fine.

## Is this specific to Cloud Shell?
No, just the version is too old.

## Interface information
All browsers are affected.

## Additional context
see https://docs.microsoft.com/en-us/azure/aks/managed-aad -> Prerequisites

**Comment by TomGeske** [comment]
PR is ready: #28

cc: @maertendMSFT

**Comment by maertendMSFT** [comment]
Closing as this PR has been merged.  The next update to Cloud Shell will happen prior to 9/21/20

**Comment by larryclaman** [comment]
just a thought: should kubectl be in the tools layer rather than the base layer?
