### ISSUE TITLE
[BUG] .profile not being run at login -> $PATH not being set correctly with user's private bin dirs

### ISSUE THREAD

**Issue by larryclaman** [Azure/CloudShell#41]
## To Reproduce

```
1. put an executable file in ~/.local/bin
2. try to run executable without full path -> it will fail as ~/.local/bin is not part of path
```

## Expected behavior

Cloud shell includes a .profile file with the following lines to set the user's local bin dir:
```
# set PATH so it includes user's private bin directories
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
```
But, it appears that .profile is not being run at login.
```
Requesting a Cloud Shell.Succeeded.
Connecting terminal...

hacker@Azure:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/linkerd/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/istio-latest/bin:/usr/local/go/bin:/opt/mssql-tools/bin:~/bundle/bin:~/bundle/gems/bin
hacker@Azure:~$
```
I am presuming that this is intended to be supported, as the .local directory exists already:
```
hacker@Azure:~$ ls -l
total 0
lrwxrwxrwx 1 hacker hacker 22 Sep 11 12:52 clouddrive -> /usr/csuser/clouddrive
hacker@Azure:~$ ls -la
total 44
drwxr-xr-x 5 hacker hacker 4096 Sep 11 12:52 .
drwxrwxrwx 3 root   root   4096 Sep 11 12:51 ..
drwx------ 5 hacker hacker 4096 Sep  9 14:33 .azure
-rw------- 1 hacker hacker 2562 Sep 11 12:54 .bash_history
-rw-r--r-- 1 hacker hacker  220 Aug 31  2015 .bash_logout
-rw-r--r-- 1 hacker hacker 4006 Sep 11 12:53 .bashrc
lrwxrwxrwx 1 hacker hacker   22 Sep 11 12:52 clouddrive -> /usr/csuser/clouddrive
drwxr-x--- 4 hacker hacker 4096 Sep 10 21:22 .kube
drwxr-xr-x 3 hacker hacker 4096 Sep  9 14:34 .local
-rwxr-xr-x 1 hacker hacker  655 Jul 12  2019 .profile
-rw-r--r-- 1 hacker hacker   42 Sep  9 14:32 .tmux.conf
-rw-r--r-- 1 hacker hacker  167 Sep 10 21:32 .wget-hsts
hacker@Azure:~$ ls -l .local
total 4
drwxr-xr-x 2 hacker hacker 4096 Sep 10 21:32 bin
hacker@Azure:~$
```

## Is this specific to Cloud Shell?
Might be specific to Cloud Shell as .profile is not being run at login.  The .profile file says:
```
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.
```
In the cloudshell environment, there is no .bash_profile nor a .bash_login, so I would assume that login would run .profile

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com, via Windows Terminal, or some other method?
If a browser, which Operating System and browser are you using? (ex. Edge on Windows 10)

**Comment by edyoung** [comment]
Thanks for the report!

Looked into this, turns out to be a bit more complicated than expected.

Issue is that bash can be started as either a login shell or a regular shell. It only looks for .profile when it is invoked as a login shell. Currently in Cloud Shell it is invoked as a regular shell. 

I considered changing that, but then it stops reading the ~/.bashrc, and discards environment vars set by the parent process, which we currently rely on. I was also a bit concerned that this could change behavior unexpectedly for some users who have customized their startup scripts.

So linked PR adds the local paths to the default PATH, but does not cause the rest of .profile to be run.
