### ISSUE TITLE
[BUG] Azure Cloud Shell no longer has ‘azcopy’ preinstalled but documentation says it should be there.

### ISSUE THREAD

**Issue by acmds** [Azure/CloudShell#450]
![GRZ4OwGW8AEnY4s](https://github.com/Azure/CloudShell/assets/100276904/eec11608-02b2-41b9-9604-1188fdd021dc)
## To Reproduce

Hello, there is an issue where Azure Cloud Shell no longer has ‘azcopy’ preinstalled, even though documentation and GitHub claim it should be in there. Please refer to the documentation and GitHub in the following links:

https://learn.microsoft.com/en-us/azure/cloud-shell/features#azure-tools and the screenshot attached. 
https://github.com/Azure/CloudShell/blob/2215e03eacb2c9ebb7086d16de99be16020f3a6b/linux/base.Dockerfile#L108

**Comment by mbifeld** [comment]
Repro'd.  Dev team is actively looking into why azcopy is not getting pre-installed properly.

**Comment by jepio** [comment]
This is related to:
- https://github.com/microsoft/azurelinux/issues/9464

**Comment by mbifeld** [comment]
Fix is releasing soon

**Comment by acmds** [comment]
[like]  Arthur Santos (Wipro Designit ... reacted to your message:
________________________________

**Comment by jepio** [comment]
The fix has been deployed, and `azcopy` works again.
