### ISSUE TITLE
[Image Update] Add oras

### ISSUE THREAD

**Issue by ridhoq** [Azure/CloudShell#454]
#### Which image would you like to change?
tools

#### What changes are you requesting?
Request is to add [`oras`](https://oras.land/) CLI to the tools image. `oras` is a CNCF Sandbox project that has gained broad adoption across the industry. Microsoft is a core maintainer of the project.

#### What scenario are these changes enabling?
The `oras` CLI enables users to interact with OCI registries such as pushing, pulling, and tagging containers and other OCI artifacts. It does not require the docker daemon to function. 

#### By how much does this change change the image size?
The latest version of `oras` is about 9.9 Mb
![image](https://github.com/user-attachments/assets/c0fd4dfc-e3bf-4ad2-b142-09b8b52918b3)

**Comment by darrentu** [comment]
Hi @ridhoq, thanks for bringing this to our attention. Since it's not available in Azure Linux, it'll be tricky for us to compliantly install this software. If you want this quickly, we recommend just installing it into your own cloud shell.
```

VERSION="1.2.0"
curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
mkdir -p ~/oras-install/
mkdir -p ~/.local/bin/
tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
mv ~/oras-install/oras ~/.local/bin/oras
rm -rf oras_${VERSION}_*.tar.gz oras-install/

```
Reference: https://oras.land/docs/installation#linux

**Comment by mbifeld** [comment]
We are currently waiting for the oras package to be available in Azure Linux.  Once it is, please raise another issue to add the package to Cloud Shell.
