### ISSUE TITLE
[BUG] mysql client was removed

### ISSUE THREAD

**Issue by rseanhall** [Azure/CloudShell#458]
## To Reproduce

This is the command that is automatically run when clicking the Connect button for a flexible mysql instance from the Azure portal:

```
mysql -h redacted.mysql.database.azure.com -u redacted -p "--ssl-ca=DigiCertGlobalRootCA.crt.pem"
```

## Observed Behavior

```
mysql: The term 'mysql' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

## Expected behavior

The mysql client should be installed in Cloud Shell.

## Is this specific to Cloud Shell?
Yes, it used to work but was removed in https://github.com/Azure/CloudShell/pull/453

## Interface information
https://portal.azure.com, Edge on Windows 11

## Additional context
Please reinstall the mysql client in Cloud Shell

**Comment by mbifeld** [comment]
The original mysql package was removed due to vulnerabilities.  We are adding the mysql client using the mariaDB package in #459 .

**Comment by surajssd** [comment]
@rseanhall is back in the CloudShell, hence closing this issue. Feel free to open issues if you face problems 🙂
