### ISSUE TITLE
[Image Update] Remove unnecessary/Unused packages from base docker image

### ISSUE THREAD

**Issue by kartikjoshi21** [Azure/CloudShell#467]
#### Which image would you like to change?
base docker image
#### What changes are you requesting?
**Text editors** : emacs, nano, vim 
**Compression tools**: xz, gzip, lz4, unzip, zip, ncompress, pigz 

**Where are we using these** => chkconfig, initscripts  

Do we need all of these packages, or are we fine with discarding unused one in base docker image ? 

#### What scenario are these changes enabling?
Removing unused packages from base docker image
#### By how much does this change change the image size?
Yet to be analyzed after discussion.

**Comment by kartikjoshi21** [comment]
cc: @surajssd

**Comment by mbifeld** [comment]
Thanks for the suggestion @kartikjoshi21 .  Since these packages do not have any vulnerability issues, we do not see a large problem keeping them for now.  We also don't collect data on commands users run, so it would be difficult to determine which of these are actually popular vs not used at all.
