### ISSUE TITLE
[BUG] How to provide a private version of Cloud Shell interactive without the Portal

### ISSUE THREAD

**Issue by hvina** [Azure/CloudShell#47]
## To Reproduce

I want to provide users a private version of an interactive shell without accessing the portal. I was able to build the image and deploy to my container registry 

When i run the command 
<code>
az acr run --registry <myRegistryName> --cmd '$Registry/sample/cloud-shell:v1 /bin/bash' /dev/null
</code>

I expect it to provide an interactive shell . 

## Observed Behavior
<code>
2020/10/02 00:46:34 Successfully executed container: acb_step_0
2020/10/02 00:46:34 Step ID: acb_step_0 marked as successful (elapsed time in seconds: 186.608901)
Run ID: ca7 was successful after 3m10s

</code>`

## Expected behavior

I expected a interactive shell prompt to be used . Can you provide instructions on how do I run that

**Comment by edyoung** [comment]
As far as I know, "az acr run" does not provide an interactive session. You will need to docker pull and docker run -it. This is a limitation in that command not in the cloud shell image.
