### ISSUE TITLE
Feature: JDK 11

### ISSUE THREAD

**Issue by aaronkorver** [Azure/CloudShell#54]
Currently only JDK 8 is installed within the shell.  Would love to see the current LTS JDK11 be available in the shell.  Perhaps something like SDKMan to help switch between the versions?

AB#14479498

**Comment by priyaananthasankar** [comment]
@aaronkorver : Currently openJDK 17 is installed in CloudShell. Would that suffice?

**Comment by priyaananthasankar** [comment]
Current version of Cloud Shell has OpenJDK 17. Closing this issue.
