### ISSUE TITLE
[BUG] URLs followed by " in shell include the " when auto-formatted to be clickable.

### ISSUE THREAD

**Issue by jainharsh98** [Azure/CloudShell#75]
Use the portal cloudshell and run the following command:

"az confluent terms list"

The command returns the following:
[
  {
    "id": "/subscriptions/eb4814af-a562-4d37-bb59-5314ae1d7926/providers/Microsoft.Confluent/agreements/marketplace",
    "name": "marketplace",
    "properties": {
      "accepted": true,
      "licenseTextLink": "https://azure.microsoft.com/en-us/support/legal/marketplace-terms/",
      "plan": "Marketplace",
      "privacyPolicyLink": "http://www.microsoft.com/privacy",
      "product": "Marketplace",
      "publisher": "Microsoft",
      "retrieveDatetime": null,
      "signature": ""
    },
    "type": "Microsoft.Confluent/agreements"
  },
  {
    "id": "/subscriptions/eb4814af-a562-4d37-bb59-5314ae1d7926/providers/Microsoft.Confluent/agreements/default",
    "name": "confluent",
    "properties": {
      "accepted": false,
      "licenseTextLink": "https://www.confluent.io/marketplace-terms-of-service/",
      "plan": "Confluent",
      "privacyPolicyLink": "https://assets.confluent.io/m/1353b6c3146e5feb/original/20200911-Confluent_Privacy_Statement.pdf",
      "product": "Marketplace",
      "publisher": "Confluent",
      "retrieveDatetime": null,
      "signature": ""
    },
    "type": "Microsoft.Confluent/offertypes"
  }
]

The licenseTextLink when clicked opens up the following URL: 
https://azure.microsoft.com/en-us/support/legal/marketplace-terms/%22/
Instead of https://azure.microsoft.com/en-us/support/legal/marketplace-terms/
Which shows a 404 response.

This is specific to cloud shell as on normal powershell the command behaves as expected.
This is an issue of the cloud shell parsing clickable urls.

**Comment by jainharsh98** [comment]
@KasifMS

**Comment by jainharsh98** [comment]
@raorugan

**Comment by raorugan** [comment]
@edyoung and @BellaLi  - Any update on this bug? We need to revert back to the partner on this.

**Comment by edyoung** [comment]
As you note, different shells have heuristics in how they search for URLs and render them clickable. In this case the code in xterm.js which handles this for cloud shell seems to have included the terminating " as part of the URL. 

In my opinion this is not a high priority issue and there is no firm time frame for us to investigate in detail, let alone fix.

**Comment by JamesFromIT** [comment]
This is also the case with URLs terminated with a full-stop in a sentence. 

![image](https://user-images.githubusercontent.com/32079449/132130404-2aca0946-708e-41ab-a66c-ef23d984a92d.png)

The link leads to [https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli.](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli.) which returns a 404 message. The actual link is [https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli](https://docs.microsoft.com/en-us/azure/storage/blobs/assign-azure-role-data-access?tabs=portal)

I came across this while working through [some Microsoft Learn content](https://docs.microsoft.com/en-us/learn/modules/control-access-to-azure-storage-with-sas/4-exercise-use-shared-access-signatures) using the sandbox feature.

**Comment by dsajanice** [comment]
URLs are now resolved correctly. We are not going to fix the fullstop issue mentioned above because we believe it is an issue with the documentation output of az storage.
