### ISSUE TITLE
[BUG] Support for Data Plane calls to APIs in Azure Quantum workspaces

### ISSUE THREAD

**Issue by ricardo-espinoza** [Azure/CloudShell#86]
## To Reproduce

Using an Azure subscription where Azure Quantum workspaces have been created, query for the list of targets in one of them.

The command below is an example considering workspace `ricardoe-portal-defprov`  in resource group `aqua-testing-westus2` and location `westus`.

```
az quantum target list -g aqua-testing-westus2 -w ricardoe-portal-defprov -l westus -o table
```

## Observed Behavior

The command fails to connect to MSI with the error output below:

```
Command group 'quantum' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
A Cloud Shell credential problem occurred. When you report the issue with the error below, please mention the hostname 'cc-28c304bc-6776f5474f-g2qs9'
Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>
```

A more detailed debug output shows the issue in the ADAL token:

```
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://quantum.microsoft.com'
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 400 714
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://quantum.microsoft.com'}
msrestazure.azure_active_directory: MSI: Failed to retrieve a token from 'http://localhost:50342/oauth2/token' with an error of '400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token'. This could be caused by the MSI extension not yet fully provisioned.
```

## Expected behavior

The command should succeed and return an object with the list of providers.

## Is this specific to Cloud Shell?
Yes.

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com, via Windows Terminal, or some other method?
Using portal.azure.com, in multiple configurations and operating systems.

## Additional context
N/A

**Comment by edyoung** [comment]
I believe this is resolved, in that we have added support for the quantum resource to the identity endpoint in Cloud Shell, but I don't have any quantum resources to test with. Could you see if this problem is resolved and reactivate if not?

**Comment by george-moussa** [comment]
@edyoung this is still failing for me. I tried the same call in the issue description and got:

Get Token request returned: {}'.format(err.response))
azure.cli.core.azclierror.AzureResponseError: Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>

cli.azure.cli.core.azclierror: Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>
az_command_data_logger: Failed to connect to MSI. Please make sure MSI is configured correctly.


Should we re-open the issue?

I gave you contributor access to a quantum workspace `/subscriptions/677fc922-91d0-4bf6-9b06-4274d319a0fa/resourceGroups/georgenm-test/providers/Microsoft.Quantum/Workspaces/contoso-canary1`

You can try these commands in cloud shell:

```
az account set --subscription 677fc922-91d0-4bf6-9b06-4274d319a0fa

az quantum target list -g georgenm-test -w contoso-canary1 -l eastus2euap -o table --debug
```

Cc: @ricardo-espinoza @danielstocker @ltalirz
