### ISSUE TITLE
[BUG] Does the GitHub CI/CD normally take this long? 

### ISSUE THREAD

**Issue by darrentu** [Azure/CloudShell#89]
## To Reproduce

I made a pull request with my code. I just made a small change to the README within the pull request.

## Observed Behavior

No official errors (at least not as of yet)

## Expected behavior

I was expecting my code to run and finish within the time slots of all the other PRs test runs.

## Is this specific to Cloud Shell?
Not exactly - maybe? Did something happen with the CloudShell pipeline code? 

## Additional context
https://github.com/Azure/CloudShell/pull/87

![Screen Shot 2021-03-23 at 6 14 59 PM](https://user-images.githubusercontent.com/12387761/112226281-58a68d00-8c04-11eb-9327-82d788cc4532.png)

**Comment by edyoung** [comment]
No, something weird happened on this run.

**Comment by darrentu** [comment]
Hmm, ok, interesting.
